# Generated by Django 4.0.4 on 2022-05-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Должность')),
                ('about', models.TextField(blank=True, db_index=True, verbose_name='Инфо')),
            ],
        ),
    ]
