# Generated by Django 4.0.4 on 2022-05-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
